"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "../components/SideNavbar";
import { AuthContextProvider, useAuthContext } from "@/context/auth";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const { user } = useAuthContext();
  // useEffect(() => {
  //   if (user == null) {
  //     router.push("/login");
  //   }
  // });
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        <AuthContextProvider>
          {/* sidebar */}
          {/* <SideNavbar /> */}

          {/* main page */}
          <div>
            {user && (
              <div className="mt-1 text-red-500 ">
                {user?.email} - {user?.role}
                <p>Attendance System 333</p>
              </div>
            )}
            <div className="p-8 w-full">{children}</div>
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
