import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "../components/SideNavbar";
// import { AuthContextProvider, useAuthContext } from "@/app/context/auth";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { ThemeProvider } from "@/components/TheamProvider";
import { getServerSession } from "next-auth";
// import FirebaseAuthProvider from './context/FirebaseAuthProvider';
import { authOptions } from "@/lib/auth";
import AuthProvider from "@/app/context/AuthProvider";
import FirebaseAuthProvider from "@/app/context/FirebaseAuthProvider";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  // const router = useRouter();
  // const { user } = useAuthContext();
  // useEffect(() => {
  //   if (user == null) {
  //     router.push("/login");
  //   }
  // });
  return (
    <html lang="en">
      <body
        className={cn(
          // "min-h-screen w-full bg-white text-black flex",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        {" "}
        <AuthProvider session={session}>
          {/* <AuthContextProvider> */}
          {/* sidebar */}
          {/* <SideNavbar /> */}
          {/* main page */}{" "}
          <div>
            {" "}
            {/* {user && (
                <div className="mt-1 text-red-500 ">
                  {user?.email} - {user?.role}
                  <p>Attendance System </p>
                </div>
              )} */}
            <div className="p-8 w-full">
              <FirebaseAuthProvider>{children}</FirebaseAuthProvider>{" "}
            </div>
          </div>{" "}
          {/* </AuthContextProvider> */}
        </AuthProvider>{" "}
      </body>
    </html>
  );
}
