import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import { cn } from "@/lib/utils";
import Sidenavbar from "./_components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          {/* sidebar */}
          <Sidenavbar />

          {/* main page */}
          <div className="p-8 w-full">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
